# https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker
version: "3.9"

services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - "${EXTERNAL_PORT:-3000}:${MB_PORT:-3000}"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE:-postgres}
      MB_DB_DBNAME: ${MB_DB_DBNAME:-metabase}
      MB_DB_USER: ${MB_DB_USER:-metabase}
      MB_DB_PASS: ${MB_DB_PASS:-metabasepassword}
      MB_DB_HOST: ${MB_DB_HOST:-db}
      MB_DB_PORT: ${MB_DB_PORT:-5432}
      JAVA_TIMEZONE: "${MB_JAVA_TIMEZONE:-Asia/Shanghai}"
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - net

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-metabase}
      POSTGRES_DB: ${POSTGRES_DB:-metabase}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-metabasepassword}
    networks:
      - net

networks:
  net:
    driver: bridge
