version: '3'

services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
      - ./data/log:/var/log/mongodb
      # - ./access.key:/etc/access.key
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf
    ports:
      - '47017:27017'
