version: '3'
networks:
  pulsar:
    driver: bridge
services:
  pulsar:
    image: apachepulsar/pulsar:2.6.0
    restart: on-failure
    networks:
      - pulsar
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    volumes:
      - "./data/pulsar/:/pulsar/data"

  dashboard:
    image: apachepulsar/pulsar-manager:v0.3.0
    restart: on-failure
    networks:
      - pulsar
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties